### ISSUE TITLE
Recommend `UpperCamelCase`for game titles

### ISSUE THREAD

**Issue by WillNilges** [ComputerScienceHouse/devcade-website#12]
On the upload screen, recommend that the binary name and game title match and are in `UpperCamelCase`.

Example:
Brick Breaker -> BrickBreaker
WrAiTh HuNt -> WraithHunt

**Comment by asimonson1125** [comment]
Did in 0ce3bca9f8fe98dd87225cc75d90693feec5aa9c for #58
