### ISSUE TITLE
Put development instance completely behind auth

### ISSUE THREAD

**Issue by WillNilges** [ComputerScienceHouse/devcade-website#34]
It Just Feels Right to me to not have our dev instance publicly available.

@asimonson1125 @wilsonmcdade thoughts?

**Comment by asimonson1125** [comment]
There may be value in allowing 'public' testing of dev games.  I think there'd have to be a security or pr reason to not allow it for us to act on that.

**Comment by wilsonmcdade** [comment]
+1 to andrews point. Another thing to consider is that when we have a public gamejam we'll need to open this dev instance up to others (or maybe create a second dev instance?)

**Comment by pikachu0542** [comment]
Closing this since there seems to be a consensus that it is worthwhile to keep dev public. Feel free to reopen if you want to discuss further
